### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'length'

### ISSUE THREAD

**Issue by ianfabs** [allain/expect#8]
When using `expect(...).toHaveLength(n)` I get this error. This is because the `in` operator does not work on strings, only on objects.

## Sample Code:
```ts
import { expect } from "https://deno.land/x/expect/mod.ts";
import { nanoid, url as urlAlphabet } from "https://deno.land/x/nanoid/mod.ts";

Deno.test({
  name: "nanoid should generate URL friendly IDs",
  fn: () => {
    for (let i = 0; i < 100; i++) {
      let id = nanoid();
      expect(id).toHaveLength(21);
      expect(typeof id).toEqual("string");
      for (let char of id) {
        expect(urlAlphabet).toContain(char);
      }
    }
  },
});
```

## Console Output:
(trimmed for brevity)
```
failures:

nanoid should generate URL friendly IDs
TypeError: Cannot use 'in' operator to search for 'length' in MuQnaGwEWSmOFUO0EEKia
    at toHaveLength (https://deno.land/x/expect/matchers.ts:327:15)
    at applyMatcher (https://deno.land/x/expect/expect.ts:100:28)
    at Proxy.<anonymous> (https://deno.land/x/expect/expect.ts:109:15)
    at fn (file:///home/fabs/Programming/nanoid/nanoid.test.ts:17:18)
    at asyncOpSanitizer ($deno$/testing.ts:36:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:70:11)
    at TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:264:22)
    at TestApi.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:346:20)
```

## Problem Area:
The issue occurs between lines 326 and 339. Here is the snippet:
```ts
export function toHaveLength(value: any, length: number): MatchResult {
  if ("length" in value && value.length === length) return { pass: true };

  const actualString = createStr(value.length);
  const lengthString = createStr(length);

  return buildFail(
    `expect(${ACTUAL}).toHaveLength(${EXPECTED})\n\n    expected array to have length ${
      green(
        lengthString,
      )
    } but was ${red(actualString)}`,
  );
}
```

Specifically, the issue occurs on line 327:

```ts
 if ("length" in value && value.length === length) return { pass: true };
```

Possibly, by changing that line to the following code, this issue will be resolved.

```ts
 if (value?.length && value.length === length) return { pass: true };
```

**Comment by allain** [comment]
Thanks for spotting this.

I've modified the code to just use:

```javascript
if (value?.length === length) return {pass:true}
```

Please let me know if your issue is resolved.

**Comment by ianfabs** [comment]
It is! Thank you so much!
